name: Build

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2025
            cmake-args:
          - name: Linux x86_64
            os: ubuntu-26.04
            cmake-args:
          - name: Linux aarch64
            os: ubuntu-26.04-arm
            cmake-args:
          - name: macOS universal
            os: macos-26
            cmake-args: -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Install SFML dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev xorg-dev
        if: startsWith(matrix.os, 'ubuntu')

      - run: cmake -B build -S . ${{ matrix.cmake-args }}
      - run: cmake --build build --config RelWithDebInfo --parallel 4
      - run: cmake --install build --config RelWithDebInfo --prefix pkg

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: pkg
